name: CI
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["6.0.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Refresh bash
        run: |
          echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
          echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc
          source ~/.bashrc
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish -c Release -o ./unvi
      - run: cd unvi
      - name: Start the application
        working-directory: ./unvi
        run: dotnet Library.WebAPI.dll
